import webbrowser
from pathlib import Path

HTML = r'''
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Grade 3 NJSLA-Style ELA Writing Practice with Score</title>
<style>
body{font-family:Arial,sans-serif;background:#f4f4f4;margin:0;color:#111}.topbar{background:#1f4e79;color:white;padding:12px 20px;display:flex;justify-content:space-between;font-size:18px}.container{max-width:1050px;margin:20px auto;background:white;padding:25px;border:1px solid #ccc;box-shadow:0 2px 6px rgba(0,0,0,.15)}.screen{display:none}.active{display:block}h1,h2,h3{color:#1f4e79}.passage{border:1px solid #999;padding:18px;margin:18px 0;line-height:1.7;font-size:18px}.prompt{border:2px solid #1f4e79;padding:18px;background:#eef5fb;font-size:18px;line-height:1.6}textarea{width:100%;height:420px;font-size:18px;line-height:1.6;padding:12px;box-sizing:border-box}button{background:#1f4e79;color:white;border:0;padding:12px 22px;font-size:16px;cursor:pointer;margin:10px 6px 0 0}button:hover{background:#163b5c}.small{font-size:14px;color:#333}.timer{font-weight:bold;font-size:20px}.review-box{border:1px solid #aaa;padding:14px;background:#fafafa;white-space:pre-wrap;font-size:17px;line-height:1.6}.score-card{border:2px solid #1f4e79;padding:16px;background:#eef5fb;margin:16px 0}table{width:100%;border-collapse:collapse;margin-top:12px;font-size:16px}th,td{border:1px solid #888;padding:10px;vertical-align:top}th{background:#e6eef7}
</style>
</head>
<body>
<div class="topbar"><div>Grade 3 ELA-Writing Practice</div><div class="timer" id="timer">90:00</div></div>
<div class="container">
<div id="screen1" class="screen active"><h1>Directions</h1><p>You will read two passages. Then you will write one response.</p><p>Your writing should answer the prompt and use details from both passages.</p><p>You will have <strong>90 minutes</strong>. A message will appear when 10 minutes remain.</p><p class="small">This is an original practice test. It is not an official NJSLA released item. The score is an automated estimate based on public Grade 3 NJSLA/PARCC-style rubric categories.</p><button onclick="startTest()">Begin Test</button></div>
<div id="screen2" class="screen"><h2>Passage 1</h2><div class="passage"><h3>The Empty Lot</h3><p>Every day, Ava walked past an empty lot on her way to school. The lot had dry dirt, broken sticks, and old paper on the ground. No one stopped there because it did not look useful.</p><p>One morning, Ava’s teacher told the class that they would start a project to improve a place in the neighborhood. Ava raised her hand and talked about the empty lot. She said it could become a small garden where people could enjoy flowers and vegetables.</p><p>On Saturday, Ava’s classmates came with gloves, small shovels, and bags for trash. First, they cleaned the lot. Then they planted seeds and watered the soil. Some students made signs reminding people to take care of the garden.</p><p>Weeks later, green plants filled the lot. Families stopped to look at the flowers. Later in the season, the class shared tomatoes and lettuce with neighbors. Ava smiled because the empty lot had become a place that helped many people.</p></div><h2>Passage 2</h2><div class="passage"><h3>The Book Cart</h3><p>Ben loved to read, but he noticed that some children in his apartment building did not have many books at home. Some children wanted to read more, but they did not know where to find books they could keep for a few days.</p><p>Ben talked to his family about the problem. His sister suggested making a small book cart for the building lobby. Ben asked classmates to donate books they had already read. Soon, he had picture books, chapter books, and books about animals and space.</p><p>Ben placed the books on a cart with a sign that said, “Take a book. Return it when you are done.” Each week, he checked the cart and added new books. Sometimes he helped younger children choose a book they might enjoy.</p><p>After a month, more children in the building were reading. Some children even wrote short notes about their favorite books. Ben felt proud because a simple idea helped others learn and enjoy stories.</p></div><button onclick="showScreen(3)">Next</button></div>
<div id="screen3" class="screen"><h2>Writing Prompt</h2><div class="prompt"><p><strong>Write an essay explaining how Ava and Ben helped their communities.</strong></p><p>Use details from both passages to support your answer.</p></div><h3>Planning Notes</h3><textarea id="notes" style="height:180px" placeholder="Plan your answer here..."></textarea><button onclick="showScreen(4)">Go to Writing</button><button onclick="showScreen(2)">Back to Passages</button></div>
<div id="screen4" class="screen"><h2>Student Response</h2><p>Write your essay in the box. Be sure to use details from both passages.</p><textarea id="response" placeholder="Type your essay here..."></textarea><br><button onclick="showScreen(5)">Review</button><button onclick="showScreen(3)">Back to Prompt</button></div>
<div id="screen5" class="screen"><h2>Review Your Writing</h2><ul><li>Did you answer the prompt?</li><li>Did you use details from both passages?</li><li>Did you organize your writing with a beginning, middle, and ending?</li><li>Did you check spelling, capitalization, and punctuation?</li></ul><h3>Your Response</h3><div id="reviewText" class="review-box"></div><button onclick="showScreen(4)">Edit Response</button><button onclick="submitTest()">Submit and Score</button></div>
<div id="screen6" class="screen"><h2>Practice Test Submitted</h2><div id="scoreOutput"></div><button onclick="downloadResponse()">Download Response and Score</button></div>
</div>
<script>
let totalSeconds=90*60,timerStarted=false,intervalId=null,warned=false,latestScoreText="";
function showScreen(num){document.querySelectorAll('.screen').forEach(s=>s.classList.remove('active'));document.getElementById('screen'+num).classList.add('active');if(num===5){document.getElementById('reviewText').innerText=document.getElementById('response').value||'(No response typed yet.)';}}
function startTest(){showScreen(2);if(!timerStarted){timerStarted=true;intervalId=setInterval(updateTimer,1000);}}
function updateTimer(){totalSeconds--;let m=Math.floor(totalSeconds/60),s=totalSeconds%60;document.getElementById('timer').innerText=String(m).padStart(2,'0')+':'+String(s).padStart(2,'0');if(totalSeconds===600&&!warned){warned=true;alert('You have 10 minutes remaining.');}if(totalSeconds<=0){clearInterval(intervalId);alert('Time is up. Your test will now be submitted and scored.');submitTest();}}
function countMatches(text,words){let c=0;for(const w of words){const re=new RegExp('\\b'+w.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')+'\\b','i');if(re.test(text))c++;}return c;}
function sentenceCount(text){return text.split(/[.!?]+/).map(x=>x.trim()).filter(x=>x.length>0).length;}
function wordCount(text){const m=text.trim().match(/\b[\w’']+\b/g);return m?m.length:0;}
function gradeResponse(text){const lower=text.toLowerCase(),words=wordCount(text),sentences=sentenceCount(text);if(words<5)return{rw:0,conv:0,total:0,percent:0,feedback:['No scoreable response or response is too short.','Write a complete answer that explains both passages.'],evidenceNotes:[]};
const avaTerms=['ava','empty','lot','garden','planted','seeds','watered','flowers','tomatoes','lettuce','neighbors','families'];
const benTerms=['ben','book','cart','books','read','reading','donate','donated','lobby','children','learn','stories'];
const communityTerms=['community','helped','people','neighbors','families','children','school','building','others'];
const orgTerms=['first','next','then','also','both','because','finally','in conclusion','for example'];
const avaScore=countMatches(lower,avaTerms),benScore=countMatches(lower,benTerms),communityScore=countMatches(lower,communityTerms),orgScore=countMatches(lower,orgTerms);
const mentionsBoth=avaScore>=2&&benScore>=2,strongEvidence=avaScore>=4&&benScore>=4,addresses=communityScore>=2||/help(ed|s)?/.test(lower),developed=words>=110&&sentences>=6,somewhat=words>=65&&sentences>=4;let rw=0;if(mentionsBoth&&addresses&&strongEvidence&&developed&&orgScore>=2)rw=3;else if(mentionsBoth&&addresses&&somewhat&&(avaScore+benScore)>=6)rw=2;else if(addresses||avaScore>=2||benScore>=2)rw=1;
const startsCapital=/^[A-Z]/.test(text.trim()),endPunct=/[.!?]\s*$/.test(text.trim()),punct=(text.match(/[.!?]/g)||[]).length,lowercaseI=/\bi\b/.test(text),runOn=sentences<=2&&words>70,avg=sentences>0?words/sentences:words,reasonable=avg<=28,repeated=countMatches(lower,['teh','becuse','becuase','comunity','peple','thay','frist','seconed']);let conv=0;if(words>=35&&startsCapital&&endPunct&&punct>=4&&reasonable&&!lowercaseI&&repeated<=1)conv=3;else if(words>=30&&endPunct&&punct>=2&&!runOn&&repeated<=3)conv=2;else if(words>=15)conv=1;
const feedback=[],notes=[];if(rw===3)feedback.push('Reading/Writing: Strong. The response answers the prompt, uses both passages, and gives relevant text-based details.');else if(rw===2)feedback.push('Reading/Writing: Adequate. The response mostly answers the prompt and uses details from both passages, but development could be stronger.');else if(rw===1)feedback.push('Reading/Writing: Limited. The response gives a partial answer, but it needs clearer details from both passages.');else feedback.push('Reading/Writing: Not yet scoreable. The response does not clearly answer the prompt.');
if(!mentionsBoth)notes.push('Use details from both Ava’s passage and Ben’s passage.');if(avaScore<4)notes.push('Add a specific detail about Ava, such as cleaning the lot, planting seeds, watering the garden, or sharing vegetables.');if(benScore<4)notes.push('Add a specific detail about Ben, such as collecting donated books, setting up a book cart, or helping children read.');if(!addresses)notes.push('Explain why the actions helped the community.');if(!developed)notes.push('Add more explanation after each detail. Do not only list what happened.');
if(conv===3)feedback.push('Conventions: Strong. Meaning is clear, with only minor or no visible issues.');else if(conv===2)feedback.push('Conventions: Adequate. Meaning is generally clear, but some grammar, punctuation, or sentence issues may remain.');else if(conv===1)feedback.push('Conventions: Limited. Check capitalization, punctuation, spelling, and complete sentences.');else feedback.push('Conventions: Not yet scoreable. The response is too short or difficult to understand.');
const total=rw+conv,percent=Math.round(total/6*100);return{rw,conv,total,percent,feedback,evidenceNotes:notes};}
function submitTest(){clearInterval(intervalId);const result=gradeResponse(document.getElementById('response').value);let html=`<div class="score-card"><h3>Estimated Final Score: ${result.total} / 6 (${result.percent}%)</h3><p><strong>Reading Comprehension and Written Expression:</strong> ${result.rw} / 3</p><p><strong>Knowledge of Language and Conventions:</strong> ${result.conv} / 3</p><p class="small">This is an automated practice score, not an official NJSLA score.</p></div><h3>Rubric-Based Feedback</h3><ul>${result.feedback.map(x=>`<li>${x}</li>`).join('')}</ul>`;if(result.evidenceNotes.length>0)html+=`<h3>How to Improve</h3><ul>${result.evidenceNotes.map(x=>`<li>${x}</li>`).join('')}</ul>`;html+=`<h3>Score Guide Used</h3><table><tr><th>Score</th><th>Reading/Writing Meaning</th><th>Conventions Meaning</th></tr><tr><td>3</td><td>Full comprehension, effective development, relevant text evidence, clear organization.</td><td>Full command of grade-level English conventions; meaning is clear.</td></tr><tr><td>2</td><td>Mostly accurate comprehension, some development, relevant evidence, mostly clear organization.</td><td>Some command of conventions; meaning is generally clear.</td></tr><tr><td>1</td><td>Limited comprehension, minimal development, weak or limited evidence.</td><td>Limited command of conventions; errors often affect understanding.</td></tr><tr><td>0</td><td>Does not demonstrate comprehension or is undeveloped/off-topic.</td><td>Frequent errors make meaning hard to understand.</td></tr></table>`;document.getElementById('scoreOutput').innerHTML=html;latestScoreText=`Estimated Final Score: ${result.total} / 6 (${result.percent}%)\nReading Comprehension and Written Expression: ${result.rw} / 3\nKnowledge of Language and Conventions: ${result.conv} / 3\n\nFeedback:\n${result.feedback.join('\n')}\n\nHow to Improve:\n${result.evidenceNotes.length?result.evidenceNotes.join('\n'):'No major improvement notes generated.'}`;showScreen(6);}
function downloadResponse(){const content='Grade 3 NJSLA-Style ELA-Writing Practice\n\n'+latestScoreText+'\n\nPlanning Notes:\n'+document.getElementById('notes').value+'\n\nStudent Response:\n'+document.getElementById('response').value+'\n';const blob=new Blob([content],{type:'text/plain'});const link=document.createElement('a');link.href=URL.createObjectURL(blob);link.download='grade3_writing_response_and_score.txt';link.click();}
</script>
</body>
</html>
'''

def main():
    out = Path('grade3_njsla_writing_practice_with_score.html').resolve()
    out.write_text(HTML, encoding='utf-8')
    print(f'Created: {out}')
    webbrowser.open(out.as_uri())

if __name__ == '__main__':
    main()
